### ISSUE TITLE
docs url down

### ISSUE THREAD

**Issue by o-az** [rovelstars/reejs#5]
https://ree.js.org/

![CleanShot 2023-07-29 at 19 08 26@2x](https://github.com/rovelstars/reejs/assets/23618431/0b4815e1-3287-4c5c-805c-4a54f79e56b6)

**Comment by renhiyama** [comment]
> https://ree.js.org/
> 
> ![CleanShot 2023-07-29 at 19 08 26@2x](https://user-images.githubusercontent.com/23618431/257021349-0b4815e1-3287-4c5c-805c-4a54f79e56b6.png)

Currently I host both reejs and [RDL](https://discord.rovelstars.com) on heroku with a single education plan account. So that means both of the websites goes down at 26th of each month and comes back online on the starting of next month, due to how 1000 hours are allocated from heroku.

I currently don't receive any donations, so that makes it hard for me to host something easily, not to mention I'm already out of money for domain renewal of my another website. If you wish to help, consider donating on my github page 🥲. I plan to work on moving them to edge later, however that still needs me some more time and I dont get that much free time like last year, exams coming up soon 😔. Hopefully you'll understand. I still try to find any free time and work on fixing bugs and introducing new features to reejs, and also research new stuff everyday.

**Comment by o-az** [comment]
do you have eth wallet address or paypal?

**Comment by renhiyama** [comment]
@o-az can u donate via github donations? It accepts only credit card I think 🤔

**Comment by o-az** [comment]
Sorry I don't donate through github anymore.

Btw did you consider hosting the sites on a different platform that won't have heroku's limits?

https://vercel.com
https://netlify.com
if you need to run a server:
https://railway.app
https://fly.io

**Comment by renhiyama** [comment]
Ah it's ok then. I would be moving to deno deploy soon anyways. Till then, you can selfhost the docs. It might even help you learn how to reejs ig!
```sh
git clone https://github.com/ree-js/website.git #clone docs
npm i -g reejs@latest #install reejs globally
cd website
npm i #runs reejs under the hood to install all the packages from import maps
reejs packit dev --node #runs a dev server for nodejs
```

**Comment by renhiyama** [comment]
@o-az just for confirmation, did you manage to run the docs locally?

**Comment by o-az** [comment]
I haven't tried. I don't have any use for reejs at the moment. I was just curious to check it out since I saw it mentioned here right before the FAQ section https://esm.sh/#cli
